channels:
- conda-forge
dependencies:
- python=3.12.0
- pip<=24.3.1
- pip:
  - mlflow==2.20.1
  - asyncio==3.4.3
  - cloudpickle==3.0.0
  - numpy==1.26.2
  - psutil==5.9.6
  - scikit-learn==1.4.0
  - scipy==1.12.0
name: mlflow-env
